# Generated by Django 5.0 on 2023-12-23 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('country', models.CharField(default='Россия', max_length=50, verbose_name='Страна')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('house_number', models.CharField(max_length=10, verbose_name='Номер дома')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Имя')),
                ('kind_of_node', models.CharField(choices=[('factory', 'Завод'), ('retail_network', 'Розничная сеть'), ('individual_entrepreneur', 'Индивидуальный предприниматель')], max_length=25, verbose_name='Тип звена')),
                ('node_level', models.IntegerField(blank=True, verbose_name='Уровень звена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('debt', models.IntegerField(default=0, verbose_name='Долг перед поставщиком')),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturers_and_retailers.contacts', verbose_name='Контакты')),
                ('supplier', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='manufacturers_and_retailers.node', verbose_name='Поставщик')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название')),
                ('model', models.CharField(max_length=64, verbose_name='Модель')),
                ('created_at', models.DateTimeField(verbose_name='Дата выхода на рынок')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturers_and_retailers.node', verbose_name='Звено')),
            ],
        ),
    ]
