# Generated by Django 5.0 on 2023-12-23 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers_and_retailers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacturers_and_retailers.node', verbose_name='Поставщик'),
        ),
    ]
