# Generated by Django 5.0 on 2023-12-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers_and_retailers', '0002_alter_node_supplier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='node',
            options={'verbose_name': 'Звено', 'verbose_name_plural': 'Звенья сети'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='node',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Долг перед поставщиком'),
        ),
    ]
